name: Deploy static content to Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # Run Bun commands
      - name: Install dependencies with Bun
        run: bun install
      - name: Run build command with Bun
        run: bun run predeploy
      - name: Run deploy command with Bun
        run: bun run deploy
